### ISSUE TITLE
Cannot process the result in resultFactory()

### ISSUE THREAD

**Issue by bubuzzz** [jedireza/mongo-models#5]
When I use mongo-models with electrode, the find function will give this exception 

`TypeError: Class constructor MongoModels cannot be invoked without 'new'`

in the place 

```
   if (Object.prototype.toString.call(result) === '[object Array]') {
      result.forEach((item, index) => {
        console.log('...... seeeefff');
        console.log(item); // have value 
        result[index] = new self(item); // exception in here 
      });
    }
```

I am not so sure this is because of babel transformation or not. This is my .babelrc

```
{
  	"presets": [ "stage-0" ], 
        "extends": "./node_modules/electrode-archetype-react-app/config/babel/.babelrc",
   	"plugins": [
	    ["babel-root-import"],
	    ["transform-runtime", {
	        "polyfill": false,
	        "regenerator": true
		}]
  	]
}

```

**Comment by jedireza** [comment]
Thanks for opening an issue.

This most likely is caused by transforming with Babel. This code was meant to be ran with node >= 4.x, which support es6 classes natively.

I did a [google search](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=babel+cannot+be+invoked+without+%27new%27), this may be relevant:

> This is because Babel's transpiled ES6 classes cannot be used to extend a real ES6 class.

Via: http://stackoverflow.com/a/32982156/1410672
